# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      # Specify the version you desire here
      # See: https://circleci.com/developer/images/image/cimg/base
      - image: cimg/base:current

    # Add steps to the job
    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
    steps:
      # Checkout the code as the first step.
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  test:
    docker:
      - image: cimg/node:20.18.0 # Use a Node.js image for running tests
    steps:
      - checkout
      # Install dependencies
      - run:
          name: Install dependencies
          command: npm run install-all
      - run:
          name: Install Oracle Instant Client
          command: |
            sudo apt-get update
            sudo apt-get install -y libaio1
            wget https://download.oracle.com/otn_software/linux/instantclient/191000/oracle-instantclient-basic-linuxx64-19.10.0.0.0dbru.zip
            unzip oracle-instantclient-basic-linuxx64-19.10.0.0.0dbru.zip
            sudo mv instantclient_19_10 /usr/local/
            sudo ln -s /usr/local/instantclient_19_10 /usr/local/instantclient
            sudo ldconfig
      - run:
          name: Create .env file
          command: |
            echo "ORACLE_USER=$ORACLE_USER" >> server/.env
            echo "ORACLE_PASSWORD=$ORACLE_PASSWORD" >> server/.env
            echo "ORACLE_CONNECT_STRING=$ORACLE_CONNECT_STRING" >> server/.env
            echo "JWT_SECRET=$JWT_SECRET" >> server/.env
      # Start the client server in the background
      - run:
          name: Start the client server
          command: |
            npm run dev &
            sleep 5

      # Start the express server in the background
      - run:
          name: Start server
          command: |
            cd server
            npm run dev &
            sleep 5        

      # Run the client tests
      - run:
          name: Run client tests
          command: npm test # Ensure your test script is defined in package.json          

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - say-hello
      - test